server:
   port: 8083

logging:
   level:
      root: INFO
      org.springframework.web: INFO
      org.springframework.security: INFO
      org.springframework.security.oauth2: INFO
      #    org.springframework.boot.autoconfigure: DEBUG
      org.springframework.web.client.RestTemplate: DEBUG
      org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
spring:
   security:
      oauth2:
         client:
            registration:
               messaging-client-client-credentials:
                  provider: spring
                  client-id: client2
                  client-secret: secret2
                  authorization-grant-type: client_credentials
                  scope: user.read, user.write, roles, openid
            provider:
               spring:
                  authorization-uri: http://127.0.0.1:8080/oauth2/authorize
                  token-uri: http://127.0.0.1:8080/oauth2/token
                  issue-uri: http://127.0.0.1:8080
messages:
   base-uri: http://127.0.0.1:8081
